#application-dev.yml
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: jtfshine0116.
  alioss:
    access-key-id: 
    access-key-secret: 
    endpoint: 
    bucket-name: 
  redis:
    port: 6379
    host: localhost
    database: 1
  wechat:
    appid: 
    secret: 
